export const postsTypes = {
  SET_POSTS: "SET_POSTS",
  ADD_COMMENTS: "ADD_COMMENTS",
  SET_COMMENT: "SET_COMMENT",
  RESET_DATA: "RESET_DATA",
  SET_LOADING: "SET_LOADING",
  DELETE_COMMENT: "DELETE_COMMENT",
  DELECTE_LIKE: "DELECTE_LIKE",
  ADD_LIKE: "ADD_LIKE",
};
