export const userTypes = {
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
  USER_ERROR: "USER_ERROR",
  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  SET_USER_POSTS: "SET_USER_POSTS",
  ADD_POST: "ADD_POST",
  SET_USER_LOADING: "SET_USER_LOADING",
  SET_SELECTED_USER_IMAGE: "SET_SELECTED_USER_IMAGE",
  RESET_SELECTED_USER_DATA: "RESET_SELECTED_USER_DATA",
  SET_PROGRESS: "SET_PROGRESS",
};
