export const userTypes = {
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
  USER_ERROR: "USER_ERROR",
  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  SET_USER_POSTS: "SET_USER_POSTS",
  ADD_POST: "ADD_POST",
};
